package view;

import controlador.MainBO;
import javax.swing.ImageIcon;
import javax.swing.JList;

/**
 *
 * @author leandro, o fura
 */
public class MapaJFrame extends javax.swing.JFrame {

    public String busca;
    public String inicio;
    public String fim;
    public MainBO controller;

    /**
     * Creates new form MapaJFrame
     */
    public MapaJFrame() {
        controller = new MainBO(this);
        initComponents();
        
        busca_cb.setEnabled(false);
        fim_cb.setEnabled(false);
        this.resolver_btn.setEnabled(false);
        
        this.setLocation(320, 150);
        this.setResizable(false);
    }

    public JList getLista(){
        return passos_ls;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        inicio_cb = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        fim_cb = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        busca_cb = new javax.swing.JComboBox();
        resolver_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        passos_ls = new javax.swing.JList();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(818, 100));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(52, 152, 30));
        jLabel14.setText("Inteligencia Artificial");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(52, 152, 30));
        jLabel18.setText("Mapa de Misantla");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel14)))
                .addContainerGap(451, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(39, 39, 39))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setOpaque(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mapa.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(52, 152, 30));
        jLabel9.setText("Inicio:");

        inicio_cb.setBackground(new java.awt.Color(118, 116, 114));
        inicio_cb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inicio_cb.setForeground(new java.awt.Color(227, 28, 28));
        inicio_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "SanJose", "Teziutlan", "Tlapacoyan", "Hupiltepec", "Martinez", "Manantiales", "Misantla", "Casitas", "SanRafael", "Vega", "Nautla", "Yecuatla", "Tenochtitlan", "Cardel", "Vencedor", "Carranza", "Raudal" }));
        inicio_cb.setFocusable(false);
        inicio_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio_cbActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(52, 152, 30));
        jLabel10.setText("Fin:");

        fim_cb.setBackground(new java.awt.Color(118, 116, 114));
        fim_cb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fim_cb.setForeground(new java.awt.Color(227, 28, 28));
        fim_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "SanJose", "Teziutlan", "Tlapacoyan", "Hupiltepec", "Martinez", "Manantiales", "Misantla", "Casitas", "SanRafael", "Vega", "Nautla", "Yecuatla", "Tenochtitlan", "Cardel", "Vencedor", "Carranza", "Raudal" }));
        fim_cb.setFocusable(false);
        fim_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fim_cbActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(52, 152, 30));
        jLabel11.setText("Algoritmo: ");

        busca_cb.setBackground(new java.awt.Color(118, 116, 114));
        busca_cb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        busca_cb.setForeground(new java.awt.Color(227, 28, 28));
        busca_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Codicioso", "A*" }));
        busca_cb.setFocusable(false);
        busca_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busca_cbActionPerformed(evt);
            }
        });

        resolver_btn.setBackground(new java.awt.Color(52, 152, 30));
        resolver_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resolver_btn.setForeground(new java.awt.Color(255, 255, 255));
        resolver_btn.setText("Resolver");
        resolver_btn.setFocusable(false);
        resolver_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolver_btnActionPerformed(evt);
            }
        });

        passos_ls.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        passos_ls.setFocusable(false);
        jScrollPane1.setViewportView(passos_ls);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(52, 152, 30));
        jLabel12.setText("Solucion:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resolver_btn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inicio_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fim_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(busca_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(inicio_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fim_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(busca_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resolver_btn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:        
    }//GEN-LAST:event_formWindowOpened

    private void inicio_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio_cbActionPerformed
        // TODO add your handling code here:
        inicio = this.inicio_cb.getModel().getSelectedItem().toString();
        if (!"-".equals(inicio)) {
            this.fim_cb.setEnabled(true);
        } else {
            this.fim_cb.setEnabled(false);
            this.busca_cb.setEnabled(false);
            this.resolver_btn.setEnabled(false);
        }
        System.out.println(inicio);
    }//GEN-LAST:event_inicio_cbActionPerformed

    private void fim_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fim_cbActionPerformed
        // TODO add your handling code here:
        fim = this.fim_cb.getModel().getSelectedItem().toString();
        if (!"-".equals(fim)) {
            this.busca_cb.setEnabled(true);
        } else {
            this.busca_cb.setEnabled(false);
            this.resolver_btn.setEnabled(false);
        }
        System.out.println(fim);
    }//GEN-LAST:event_fim_cbActionPerformed

    private void busca_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busca_cbActionPerformed
        // TODO add your handling code here:
        busca = this.busca_cb.getModel().getSelectedItem().toString();
        if (!"-".equals(busca)) {
            this.resolver_btn.setEnabled(true);
        } else {
            this.resolver_btn.setEnabled(false);
        }
        System.out.println(busca);
    }//GEN-LAST:event_busca_cbActionPerformed

    private void resolver_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolver_btnActionPerformed
        // TODO add your handling code here:
        this.controller.resolve(busca);
    }//GEN-LAST:event_resolver_btnActionPerformed

    /*
    protected static ImageIcon createImageIcon(String path,
            String description) {
        java.net.URL imgURL = MapaJFrame.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL, description);
        } else {
            System.err.println("Não conseguiu encontrar a imagem: " + path);
            return null;
        }
    }*/

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox busca_cb;
    private javax.swing.JComboBox fim_cb;
    private javax.swing.JComboBox inicio_cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList passos_ls;
    private javax.swing.JButton resolver_btn;
    // End of variables declaration//GEN-END:variables
}
